// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import localFont from 'next/font/local';


export const metadata: Metadata = {
  title: "MTN ACADEMY",
  description: "Generated by AE & ROMAMPH DEV TEAM",
};

// Initialize Poppins font
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-poppins',
});

const cairo = localFont({
  src: '../public/fonts/Cairo-Regular.ttf', // Add your Arabic font file
  variable: '--font-cairo',
  display: 'swap',
});


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" >
      <body className={`${poppins.variable} ${cairo.variable}`}>{children}</body>
    </html>
  );
}
